#!/bin/bash

set -euxo pipefail

set_repo_dir()
{
    if [[ -n ${BASH_SOURCE[0]} ]]; then
        script_path="${BASH_SOURCE[0]}"
    else
        script_path="$0"
    fi

    script_dir="$(dirname "$(realpath "$script_path")")"
    repo_dir="$(dirname "$script_dir")"

}

install_packages_apt()
{
    echo 'Installing script dependencies...'

    # apt-get update and install dependencies
    sudo apt-get update && sudo apt-get --no-install-recommends install -y coreutils \
        git-lfs \
        unzip \
        dialog \
        wget \
        curl \
        fzf \
        build-essential
}

install_packages_opkg()
{
   echo 'opkg not supported currently' && false
}

install_packages_rpm()
{
    echo 'rpm not supported currently' && false
}

install_brew()
{
    echo 'Installing brew...'
    command -v brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"


}

install_packages_brew()
{
    echo 'Installing brew packages...'
    brew install \
        coreutils \
        openjdk@11 \
        grep \
        fzf \
        wget \
        starship \
        pyenv

    if [[ ! -f fzf_installed ]]; then
        /opt/homebrew/opt/fzf/install
        touch fzf_installed
    fi
}

install_packages_source()
{
    echo 'source not supported currently' && false
}

install_packages_pip3()
{
    pip3 install -U pip
}

install_packages()
{
    PM=none
    if command -v apt-get; then
        PM=apt
    elif command -v rpm; then
        PM=rpm
    elif command -v opkg; then
        PM=opkg
    elif command -v brew; then
        PM=brew
    elif command -v source; then
        PM=source
    else
        echo 'No supported package managers detected.' && false
        exit 1
    fi

    install_packages_$PM

    if command -v pip3; then
        install_packages_pip3
    fi
}

bootstrap_zsh()
{
    echo "Bootstrapping zsh"

    if ! command -v zsh; then
        if command -v apt; then
            sudo apt install zsh
        elif command -v brew; then
            brew install zsh
        fi
    fi

    # Install oh-my-zsh
    if [ ! -d "${HOME}/.oh-my-zsh" ]; then
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi

    # Link .zshrc into $HOME
    if [ -f "${HOME}/.zshrc" ]; then
        while true; do
            printf "Remove existing \e[31m~/.zshrc\e[0m? [y/n]"
            read yn
            case $yn in
                [Yy]* )
                    rm ~/.zshrc
                    ln -s ${repo_dir}/.zshrc ~
                    break;;
                [Nn]* ) break;;
                * ) echo "Please answer yes or no.";;
            esac
        done
    fi

    # Clone non-default zsh plugins
    plugins=(
        zsh-autosuggestions
    )

    # Source this for 'gitCloneOrPull'
    source ${repo_dir}/utils/bash_utils.sh

    for plugin in ${plugins[@]}; do
        plugin_repo=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/${plugin}
        gitCloneOrPull $plugin_repo https://github.com/zsh-users/${plugin}
    done

    gitCloneOrPull \
        ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting \
        https://github.com/zdharma-continuum/fast-syntax-highlighting.git

}

bootstrap_mac()
{
    echo "Bootstrapping mac"
    return
}

main()
{
    if [[ "$OSTYPE" == "darwin"* ]]; then
        install_brew
    fi

    install_packages

    if [ ! -d "${HOME}/.pyenv" ]; then
        echo "Installing pyenv"
        curl https://pyenv.run | bash
    fi

    set_repo_dir

    if [ ! -d "${HOME}/.oh-my-zsh" ]; then bootstrap_zsh; fi

    # macOS specific bootstrap
    if [[ "$OSTYPE" == "darwin"* ]]; then
        bootstrap_mac
    fi

    echo "Bootstrap completed successfully."
}

main


if [ -f $ZSH/plugins/git/git.plugin.zsh ] && [ ! -f $ZSH/plugins/git/patched ]; then
    git -C $ZSH apply $repo_dir/patches/gs-alias.patch
    touch $ZSH/plugins/git/patched
fi
