#!/bin/bash

if [[ -n ${BASH_SOURCE[0]} ]]; then
    script_path="${BASH_SOURCE[0]}"
else
    script_path="$0"
fi

script_dir="$(dirname "$(realpath "$script_path")")"
repo_dir="$(dirname "$script_dir")"

set -euxo pipefail

install_packages_apt()
{
    echo 'Installing script dependencies...'

    # apt-get update and install dependencies
    sudo apt-get update && sudo apt-get --no-install-recommends install -y coreutils \
        git-lfs \
        unzip \
        dialog
}

install_packages_opkg()
{
   echo 'opkg not supported currently' && false
}

install_packages_rpm()
{
    echo 'rpm not supported currently' && false
}

install_packages_brew()
{
    echo 'Installing brew...'
    command -v brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    echo 'Installing brew packages...'
    brew install \
        coreutils \
        openjdk@11 \
        grep \
        fzf

    /opt/homebrew/opt/fzf/install
}

install_packages_source()
{
    echo 'source not supported currently' && false
}

install_packages_pip3()
{
    pip3 install -U pip
}

install_packages()
{
    PM=source
    if command -v apt-get; then
        PM=apt
    elif command -v rpm; then
        PM=rpm
    elif command -v opkg; then
        PM=opkg
    elif command -v brew; then
        PM=brew
    fi
    install_packages_$PM

    if command -v pip3; then
        install_packages_pip3
    fi
}

bootstrap_zsh()
{
    plugins=(
        zsh-autosuggestions
        zsh-syntax-highlighting
    )

    # Source this for 'gitCloneOrPull'
    source ${repo_dir}/utils/bash_utils.sh

    for plugin in ${plugins[@]}; do
        plugin_repo=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/${plugin}
        gitCloneOrPull $plugin_repo https://github.com/zsh-users/${plugin}
    done
}

main()
{
    install_packages

    echo "Bootstrapping zsh"
    bootstrap_zsh

    # macOS specific bootstrap
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Bootstrapping mac"
        bootstrap_mac
    fi

    if [[ "$USER" == "matran"* ]]; then
        echo "Bootstrapping silabs"
        ${script_dir}/bootstrap_silabs
    fi

    echo "Bootstrap completed successfully."
}

main

bootstrap_mac()
{
    return
}


if [ -f $ZSH/plugins/git/git.plugin.zsh ] && [ ! -f $ZSH/plugins/git/patched ]; then
    git -C $ZSH apply $repo_dir/patches/gs-alias.patch
    touch $ZSH/plugins/git/patched
fi

